

const ActionTypes = {
  ADD_TODO: 'ADD_TODO',
  DELETE_COMPLETED_TODOS: 'DELETE_COMPLETED_TODOS',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  START_EDITING_TODO: 'START_EDITING_TODO',
  STOP_EDITING_TODO: 'STOP_EDITING_TODO',
  TOGGLE_ALL_TODOS: 'TOGGLE_ALL_TODOS',
  TOGGLE_TODO: 'TOGGLE_TODO',
  UPDATE_DRAFT: 'UPDATE_DRAFT',
  GET_PROJECTDATA: 'GET_PROJECTDATA',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  GET_PROJECT_DONE: 'GET_PROJECT_DONE',
  GET_TOTAL_CLIENT: 'GET_TOTAL_CLIENT',
};

export default ActionTypes;
